export const GET_CHAT_MESSAGES_REQUEST = 'GET_CHAT_MESSAGES_REQUEST';
export const GET_CHAT_MESSAGES_SUCCESS = 'GET_CHAT_MESSAGES_SUCCESS';
export const GET_CHAT_MESSAGES_ERROR = 'GET_CHAT_MESSAGES_ERROR';
export const GET_NEW_PRIVATE_MESSAGE = 'GET_NEW_PRIVATE_MESSAGE';