export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_ERROR = 'USER_SIGN_UP_ERROR';

export const USER_SIGN_OUT = 'USER_SIGN_OUT';

export const GET_ACTIVE_USERS_REQUEST = 'GET_ACTIVE_USERS_REQUEST';
export const GET_ACTIVE_USERS_ERROR = 'GET_ACTIVE_USERS_ERROR';
export const GET_ACTIVE_USERS_SUCCESS = 'GET_ACTIVE_USERS_SUCCESS';

export const NEW_USER_JOIN = 'NEW_USER_JOIN';
export const USER_DISONNECTED = 'USER_DISONNECTED';